config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#new'
  resources :tasks
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  scope :complete, -> { where(status: true) }
  scope :incomplete, -> { where(status: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
		@notes = Note.all 
	end

	def show
		@note = Note.find(params[:id])
	end

	def destroy
		@note = Note.find(params[:id])
		@note.destroy
		redirect_to notes_url 
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task, only: [:show, :update, :destroy]

  def show
  end

  def new
    @task = Task.new
    @notes = Note.last(3)
  end

  def create
    @task = Task.new(tasks_params)

    if @task.save
      redirect_to new_task_url
    else
      render :new
    end
  end

  def update
    @task.update_attribute(:status, tasks_params[:status]) if @task
    redirect_to new_task_url
  end

  def destroy
    @task.destroy
    redirect_to new_task_url
  end

  private

  def tasks_params
    params.require(:task).permit(:id, :name, :status)
  end

  def task
    @task ||= Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksTurbolinks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p>
  		<%= link_to 'tasks', new_task_path %>
  		<%= link_to 'notes', notes_path %>
  	</p>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<div class="row">
	<h3>Notes</h3>
	<% @notes.each do |note| %>
		<p>
			<%= note.title %>
			<%= link_to 'show', note_path(note) %>
			<%= link_to 'delete', note_path(note), method: :delete %>
		</p>
	<% end %>
</div>

app/views/notes/show.html.erb
<h3>Notes</h3>
<p>title: <%= @note.title %></p>
<p>note: <%= @note.content %></p>
<p>created: <%= time_ago_in_words(@note.created_at) %> ago </p>

app/views/tasks/_task.html.erb
<%= form_for task, render: true do |f| %>
	<%= f.check_box :status, data: {behaviour: 'completed'} %>
	<%= task.name %>
	<%= link_to 'delete', task_path(task), remote: true, method: :delete %>
	<%= link_to 'show', task_path(task) %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task, remote: true do |f| %>
	<%= f.text_field :name %>
	<%= f.submit 'Create Task' %>
<% end %>

<h3>Incomplete</h3>
<%= render Task.incomplete %>

<h3>Complete</h3>
<%= render Task.complete %>

<h3>Notes</h3>
<% @notes.each do |note| %>
	<p><%= note.title %> <%= link_to 'delete', note_path(note), method: :delete %></p>
<% end %>

app/views/tasks/show.html.erb
<h3>Task</h3>
<p>task: <%= @task.name %></p>
<p>Completed? <%= @task.status %></p>
<p>created: <%= time_ago_in_words(@task.created_at) %> ago</p>